
name: 'Build the website'

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout `master`'
        uses: actions/checkout@v2.3.4

      - name: 'Checkout `gh-pages` into a separate directory'
        uses: 'actions/checkout@v2.3.4'
        with:
          path: 'dist'
          ref: 'gh-pages'

      - name: 'Download Pandoc'
        shell: bash
        run: .github/workflows/download-pandoc.sh

      - name: 'Download Sass'
        shell: bash
        run: .github/workflows/download-sass.sh

      - name: 'Render the website'
        shell: bash
        run: ./build.sh

      - name: 'Get current time'
        uses: gerred/current-time@v1.0.0
        id: current-time

      - name: 'push the changes'
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "deployed on ${{ steps.current-time.outputs.time }}"
          branch: 'gh-pages'
          cwd: './dist/'
          add: './*'
